site_name: PyAPI Client
site_url: https://pyapi-client.readthedocs.io
repo_url: https://github.com/berislavlopac/pyapi-client
site_description: Python client library for making requests to any OpenAPI-based service.
site_author: Berislav Lopac <berislav@lopac.net>
theme:
  name: material
  icon:
    logo: material/power-socket-uk
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Introduction: 'index.md'
