[tox]
requires =
    tox>=4
    tox-uv
isolated_build = true
envlist = checks, py310, py311, py312, py313, py314

[testenv]
skip_install = true
runner = uv-venv-lock-runner
dependency_groups =
    dev
commands =
    pytest --cov --spec --junitxml=test-reports{/}{envname}-junit.xml
    coverage xml -o test-reports{/}{envname}-coverage.xml
    mypy --install-types --non-interactive

[testenv:checks]
commands =
    ruff format --check .
    ruff check .
    mypy --install-types --non-interactive